### ISSUE TITLE
[JOSS Review] Manuscript Comments

### ISSUE THREAD

**Issue by sreschechtko** [SwathiSheshadri/pose3d#1]
There are a few points in the Manuscript I believe should be addressed before the packages is recommended for publication in JOSS:

1) Paper should emphasize applicability beyond DeepLabCut (as per pre-review concerns)

2) Paper should more directly compare functionality to common alternatives, especially anipose

3) Paper summary could be for a less specialist audience, e.g. explain the issue it addresses in less technical terms. (Presumably some of the appeal of this package is to less specialist audience since they want to use the MATLAB calibration GUI.)

**Comment by SwathiSheshadri** [comment]
We have updated the paper.md file to emphasize pose3d’s applicability beyond DLC. Also, we have included a section comparing pose3d to anipose and extended the paper summary by including a more detailed and less technical description of the issues addressed by pose3d. The changes made specifically to address the 3 issues are listed below: 

1.	The last few lines of the first paragraph have been modified to address this comment.

2.	Two new sections to address this have been added titled ‘Comparison of pose3d to existing Matlab functions’ and ‘Comparison of pose3d and anipose‘

3.	The second paragraph of the paper is majorly modified to address this issue. Furthermore, an additional section called ‘pose3d usage and features’ has been added.
