### ISSUE TITLE
[JOSS Review] Visualize previously saved calibration data

### ISSUE THREAD

**Issue by danasolav** [SwathiSheshadri/pose3d#10]
Is it possible to open the calibration GUI with the results of a pre-saved calibration file? If not, that would be a great feature to add.

**Comment by SwathiSheshadri** [comment]
I agree, it is definitely a very nice feature to have! I have now updated the code at pose3d repository to load pre-existing calibration files when the users choose to redo calibration when running pose3d. After looking at the results of previous calibration they can decide if they want to recalibrate for the select pair. The same visualisation follows for all pairs sequentially and the users can now selectively decide which pair they want to recalibrate.
