### ISSUE TITLE
how to annotate the 2D hand keypoints in every frame?

### ISSUE THREAD

**Issue by aqsc** [SwathiSheshadri/pose3d#11]
how to annotate the 2D hand keypoints in every frame?

**Comment by SwathiSheshadri** [comment]
There are many tools that can be used to carry out annotations. However, DeepLabCut offers an integrated annotation/training platform. Check it out : [https://github.com/DeepLabCut/DeepLabCut](https://github.com/DeepLabCut/DeepLabCut)
