### ISSUE TITLE
[JOSS Review] Enhance calibration instructions

### ISSUE THREAD

**Issue by sreschechtko** [SwathiSheshadri/pose3d#2]
The instructions should include a section on collecting calibration images or videos. Ideally the package would include the ability to create calibration checkerboards, but if it it should link to a source for them.

**Comment by SwathiSheshadri** [comment]
We added a new section 'Checkerboard images or videos for calibration' to the readme file with instructions on collecting calibration images/videos. In the same section, instructions on obtaining and printing checkerboard layout that can be used for calibration purposes is included. Typing 'open checkerboardPattern.pdf' in Matlab command line allows users access to a checkerboard which can then be printed out. In addition, the ‘DemoExperiments’ folder contains a folder named ‘Imagesforcalibration’, in which we have included the calibration images we have used for our 5-camera recording system.
