### ISSUE TITLE
[JOSS Review]  Relax requirement for calibration videos to have unique names

### ISSUE THREAD

**Issue by sreschechtko** [SwathiSheshadri/pose3d#4]
The requirement that calibration videos cannot be duplicated is overly onerous. If a user records a set of calibration videos on a syncronized camera system, they are currently required to duplicate the primary video as many times as there are pairs, and name these unique names even though they are the same video. This wastes disk space and is annoying when producing a calibration dataset. I recommend relaxing this constraint.

**Comment by SwathiSheshadri** [comment]
Thank you for this helpful suggestion. The requirement came about from our specific use case, in which the user can select and record selectively from pairs of cameras. However, we agree that this procedure would not be accommodative in general. In line with your suggestion, we have therefore relaxed this requirement: pose3d now allows the option to have a single primary calibration video.
