### ISSUE TITLE
[JOSS Review] Enhance Troubleshooting section

### ISSUE THREAD

**Issue by sreschechtko** [SwathiSheshadri/pose3d#5]
Troubleshooting topics are vague and do not provide context for identifying what these errors look like at runtime. It would be much improved by showing demonstrations of the error output (either screenshots/gifs or explanations) of these failure modes so users can diagnose them.

**Comment by SwathiSheshadri** [comment]
To address this issue, we have included in the section renamed ‘Video tutorial and troubleshooting’ video tutorials on using pose3d and added elaborated explanations to the trouble shooting section.

**Comment by sreschechtko** [comment]
Thanks, I think the video tutorials are helpful. On a high resolution display, I had a hard time following the tutorial because the text was very small.  I  will close this issue but would recommend either adding more explanatory subtitles, using magnification, or including a separate text file with the tasks you carry out and timestamps when you are doing them.
