### ISSUE TITLE
[JOSS Review] Include performance verification ability

### ISSUE THREAD

**Issue by sreschechtko** [SwathiSheshadri/pose3d#6]
Package would be much more useful if it included automatic functionality for performance verification. This is another feature which is available in the demo but not actually implemented. For example, it would be great to add an option in the configuration to input real segment length(s) and compare the(se) length(s) to the computed length(s) from reconstruction.

**Comment by SwathiSheshadri** [comment]
The code was developed under the assumption of unavailability of ground truth data. However, we see your point that many experiments might indeed have ground truth available. We therefore added this functionality as an optional feature in the package. It can be used by editing the variables calc_error and ground_truth in the config file. Average and standard deviation in the error across all frames and line segments on the skeleton will be displayed at the successful termination of main_pose3d script. Details on errors at individual frames and line segments can also be accessed from the workspace variable errorinrecon (frames x linesegments x mode).

**Comment by sreschechtko** [comment]
Thanks for adding this functionality. I think it helps separate your software from other currently available options. I will close this issue but would suggest altering the implementation slightly so that we can track a subset of the segments rather than all of them. This would make it easier to use because the end user could make only a small number of "ground truth" measurements. For example, if tracking a hand, it is relatively easy to measure one segment during research, but measuring and inputting all segments is quite onerous.
