### ISSUE TITLE
[JOSS Review] Improvement suggestion

### ISSUE THREAD

**Issue by danasolav** [SwathiSheshadri/pose3d#9]
It would be great if a new set of tracking data could be run with previously saved calibration files. Currently it seems like both calibration and reconstruction have to be run together. However, I think it's common to have a camera setup where you run new experiments with the same camera configuration, and it could be helpful to avoid re-running the calibration every time.
This could be done by wither adding an option of selecting a calibration file instead of video/images or by separating the main code into two main codes (1-calibration, 2-reconstruction and plotting).

**Comment by danasolav** [comment]
OK, I just found out that it IS possible to use a pre-saved calibration file. However, the structure of the folders and sub-folders has to be better explained in the readme file and in the config file, because the code only "finds" the calibration file if it's saved in the correct location.

**Comment by SwathiSheshadri** [comment]
Thank you for pointing it out. I think it will definitely help users to have this documented in the readme file. I have now updated the section 'Using pose3d for your data' in the readme file to highlight this point.
